FROM python:{{python_version}}-slim as builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV UV_LINK_MODE=copy
ENV UV_COMPILE_BYTECODE=1
ENV UV_PROJECT_ENVIRONMENT=/opt/venv

WORKDIR /app

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

FROM python:{{python_version}}-slim
COPY --from=builder /opt/venv /opt/venv

RUN apt-get update && apt-get install -y curl

COPY ./server /app
CMD ["/opt/venv/bin/fastapi", "run", "server/main.py", "--reload", "--host", "0.0.0.0", "--port", "8000"]
